// https://protobuf.dev/programming-guides/proto3/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package helloworld

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumerationValue int32

const (
	EnumerationValue_VALUE0 EnumerationValue = 0
	EnumerationValue_VALUE1 EnumerationValue = 1
	EnumerationValue_VALUE2 EnumerationValue = 2
)

// Enum value maps for EnumerationValue.
var (
	EnumerationValue_name = map[int32]string{
		0: "VALUE0",
		1: "VALUE1",
		2: "VALUE2",
	}
	EnumerationValue_value = map[string]int32{
		"VALUE0": 0,
		"VALUE1": 1,
		"VALUE2": 2,
	}
)

func (x EnumerationValue) Enum() *EnumerationValue {
	p := new(EnumerationValue)
	*p = x
	return p
}

func (x EnumerationValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumerationValue) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (EnumerationValue) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x EnumerationValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumerationValue.Descriptor instead.
func (EnumerationValue) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type ScalarValueTypes struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Double   float64                `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	Float    float32                `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	Int32    int32                  `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64    int64                  `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32   uint32                 `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64   uint64                 `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Sint32   int32                  `protobuf:"zigzag32,7,opt,name=sint32,proto3" json:"sint32,omitempty"`
	Sint64   int64                  `protobuf:"zigzag64,8,opt,name=sint64,proto3" json:"sint64,omitempty"`
	Fixed32  uint32                 `protobuf:"fixed32,9,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64  uint64                 `protobuf:"fixed64,10,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32 int32                  `protobuf:"fixed32,11,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64 int64                  `protobuf:"fixed64,12,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool     bool                   `protobuf:"varint,13,opt,name=bool,proto3" json:"bool,omitempty"`
	String_  string                 `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Bytes    []byte                 `protobuf:"bytes,15,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Array    []string               `protobuf:"bytes,16,rep,name=array,proto3" json:"array,omitempty"`
	// https://protobuf.dev/programming-guides/proto3/#maps
	Map map[string]int32 `protobuf:"bytes,17,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// https://protobuf.dev/programming-guides/proto3/#enum
	Enumvalue EnumerationValue `protobuf:"varint,18,opt,name=enumvalue,proto3,enum=helloworld.EnumerationValue" json:"enumvalue,omitempty"`
	// https://protobuf.dev/programming-guides/proto3/#oneof
	//
	// Types that are valid to be assigned to Oneofname:
	//
	//	*ScalarValueTypes_Oneint32
	//	*ScalarValueTypes_Onestring
	Oneofname     isScalarValueTypes_Oneofname `protobuf_oneof:"oneofname"`
	Any           *anypb.Any                   `protobuf:"bytes,21,opt,name=any,proto3" json:"any,omitempty"`
	Timestamp     *timestamppb.Timestamp       `protobuf:"bytes,22,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarValueTypes) Reset() {
	*x = ScalarValueTypes{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarValueTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarValueTypes) ProtoMessage() {}

func (x *ScalarValueTypes) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarValueTypes.ProtoReflect.Descriptor instead.
func (*ScalarValueTypes) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarValueTypes) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

func (x *ScalarValueTypes) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

func (x *ScalarValueTypes) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *ScalarValueTypes) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

func (x *ScalarValueTypes) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *ScalarValueTypes) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *ScalarValueTypes) GetSint32() int32 {
	if x != nil {
		return x.Sint32
	}
	return 0
}

func (x *ScalarValueTypes) GetSint64() int64 {
	if x != nil {
		return x.Sint64
	}
	return 0
}

func (x *ScalarValueTypes) GetFixed32() uint32 {
	if x != nil {
		return x.Fixed32
	}
	return 0
}

func (x *ScalarValueTypes) GetFixed64() uint64 {
	if x != nil {
		return x.Fixed64
	}
	return 0
}

func (x *ScalarValueTypes) GetSfixed32() int32 {
	if x != nil {
		return x.Sfixed32
	}
	return 0
}

func (x *ScalarValueTypes) GetSfixed64() int64 {
	if x != nil {
		return x.Sfixed64
	}
	return 0
}

func (x *ScalarValueTypes) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *ScalarValueTypes) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *ScalarValueTypes) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *ScalarValueTypes) GetArray() []string {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *ScalarValueTypes) GetMap() map[string]int32 {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *ScalarValueTypes) GetEnumvalue() EnumerationValue {
	if x != nil {
		return x.Enumvalue
	}
	return EnumerationValue_VALUE0
}

func (x *ScalarValueTypes) GetOneofname() isScalarValueTypes_Oneofname {
	if x != nil {
		return x.Oneofname
	}
	return nil
}

func (x *ScalarValueTypes) GetOneint32() int32 {
	if x != nil {
		if x, ok := x.Oneofname.(*ScalarValueTypes_Oneint32); ok {
			return x.Oneint32
		}
	}
	return 0
}

func (x *ScalarValueTypes) GetOnestring() string {
	if x != nil {
		if x, ok := x.Oneofname.(*ScalarValueTypes_Onestring); ok {
			return x.Onestring
		}
	}
	return ""
}

func (x *ScalarValueTypes) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *ScalarValueTypes) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isScalarValueTypes_Oneofname interface {
	isScalarValueTypes_Oneofname()
}

type ScalarValueTypes_Oneint32 struct {
	Oneint32 int32 `protobuf:"varint,19,opt,name=oneint32,proto3,oneof"`
}

type ScalarValueTypes_Onestring struct {
	Onestring string `protobuf:"bytes,20,opt,name=onestring,proto3,oneof"`
}

func (*ScalarValueTypes_Oneint32) isScalarValueTypes_Oneofname() {}

func (*ScalarValueTypes_Onestring) isScalarValueTypes_Oneofname() {}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\n" +
	"helloworld\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x05\n" +
	"\x10ScalarValueTypes\x12\x16\n" +
	"\x06double\x18\x01 \x01(\x01R\x06double\x12\x14\n" +
	"\x05float\x18\x02 \x01(\x02R\x05float\x12\x14\n" +
	"\x05int32\x18\x03 \x01(\x05R\x05int32\x12\x14\n" +
	"\x05int64\x18\x04 \x01(\x03R\x05int64\x12\x16\n" +
	"\x06uint32\x18\x05 \x01(\rR\x06uint32\x12\x16\n" +
	"\x06uint64\x18\x06 \x01(\x04R\x06uint64\x12\x16\n" +
	"\x06sint32\x18\a \x01(\x11R\x06sint32\x12\x16\n" +
	"\x06sint64\x18\b \x01(\x12R\x06sint64\x12\x18\n" +
	"\afixed32\x18\t \x01(\aR\afixed32\x12\x18\n" +
	"\afixed64\x18\n" +
	" \x01(\x06R\afixed64\x12\x1a\n" +
	"\bsfixed32\x18\v \x01(\x0fR\bsfixed32\x12\x1a\n" +
	"\bsfixed64\x18\f \x01(\x10R\bsfixed64\x12\x12\n" +
	"\x04bool\x18\r \x01(\bR\x04bool\x12\x16\n" +
	"\x06string\x18\x0e \x01(\tR\x06string\x12\x14\n" +
	"\x05bytes\x18\x0f \x01(\fR\x05bytes\x12\x14\n" +
	"\x05array\x18\x10 \x03(\tR\x05array\x127\n" +
	"\x03map\x18\x11 \x03(\v2%.helloworld.ScalarValueTypes.MapEntryR\x03map\x12:\n" +
	"\tenumvalue\x18\x12 \x01(\x0e2\x1c.helloworld.EnumerationValueR\tenumvalue\x12\x1c\n" +
	"\boneint32\x18\x13 \x01(\x05H\x00R\boneint32\x12\x1e\n" +
	"\tonestring\x18\x14 \x01(\tH\x00R\tonestring\x12&\n" +
	"\x03any\x18\x15 \x01(\v2\x14.google.protobuf.AnyR\x03any\x128\n" +
	"\ttimestamp\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\v\n" +
	"\toneofname\"#\n" +
	"\aMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*6\n" +
	"\x10EnumerationValue\x12\n" +
	"\n" +
	"\x06VALUE0\x10\x00\x12\n" +
	"\n" +
	"\x06VALUE1\x10\x01\x12\n" +
	"\n" +
	"\x06VALUE2\x10\x022\xf4\x01\n" +
	"\x03Api\x12B\n" +
	"\x04Call\x12\x1c.helloworld.ScalarValueTypes\x1a\x1c.helloworld.ScalarValueTypes\x129\n" +
	"\bDownload\x12\x16.google.protobuf.Empty\x1a\x13.helloworld.Message0\x01\x127\n" +
	"\x06Upload\x12\x13.helloworld.Message\x1a\x16.google.protobuf.Empty(\x01\x125\n" +
	"\x05Async\x12\x13.helloworld.Message\x1a\x13.helloworld.Message(\x010\x01b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(EnumerationValue)(0),         // 0: helloworld.EnumerationValue
	(*ScalarValueTypes)(nil),      // 1: helloworld.ScalarValueTypes
	(*Message)(nil),               // 2: helloworld.Message
	nil,                           // 3: helloworld.ScalarValueTypes.MapEntry
	(*anypb.Any)(nil),             // 4: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_service_proto_depIdxs = []int32{
	3, // 0: helloworld.ScalarValueTypes.map:type_name -> helloworld.ScalarValueTypes.MapEntry
	0, // 1: helloworld.ScalarValueTypes.enumvalue:type_name -> helloworld.EnumerationValue
	4, // 2: helloworld.ScalarValueTypes.any:type_name -> google.protobuf.Any
	5, // 3: helloworld.ScalarValueTypes.timestamp:type_name -> google.protobuf.Timestamp
	1, // 4: helloworld.Api.Call:input_type -> helloworld.ScalarValueTypes
	6, // 5: helloworld.Api.Download:input_type -> google.protobuf.Empty
	2, // 6: helloworld.Api.Upload:input_type -> helloworld.Message
	2, // 7: helloworld.Api.Async:input_type -> helloworld.Message
	1, // 8: helloworld.Api.Call:output_type -> helloworld.ScalarValueTypes
	2, // 9: helloworld.Api.Download:output_type -> helloworld.Message
	6, // 10: helloworld.Api.Upload:output_type -> google.protobuf.Empty
	2, // 11: helloworld.Api.Async:output_type -> helloworld.Message
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[0].OneofWrappers = []any{
		(*ScalarValueTypes_Oneint32)(nil),
		(*ScalarValueTypes_Onestring)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
